### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by richelbilderbeek** [jorn600/the-bilderbeek-style#3]
Thanks Jorn for this very important GitHub.

There is a typo in the title though:

![issue](https://cloud.githubusercontent.com/assets/2098230/20237576/e46ec7f0-a8d6-11e6-87ba-95f1f5a8f964.png)

I hope you'll fix it.

**Comment by JornPrengerFormeel** [comment]
Fixed it

**Comment by richelbilderbeek** [comment]
Indeed, some errors have been fixed. But not in the _title_ yet.

**Comment by thijsvb** [comment]
Only the owner of the repository can edit the description... _cough_ @jorn600 _cough_

**Comment by richelbilderbeek** [comment]
Well done [whoever did that]!
